# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2024, MediaTek

BINARY = 692b0623-850a-46ca-a431-763f7d9459b4

include $(OPTEE_OS_DIR)/mk/conf.mk

CPPFLAGS += -I../include
CPPFLAGS += -I./include

# Include OP-TEE TA development kit
include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
